export const certifications = [
  {
    id: "DSRVIU40D9LE",
    name: "Google Advanced Data Analytics Professional Certificate",
    issuer: "Google",
    date: "2024",
    link: "https://www.coursera.org/account/accomplishments/specialization/DSRVIU40D9LE",
    featured: true
  },
  {
    id: "GE9XM1DZBFLK",
    name: "Google IT Automation with Python Professional Certificate",
    issuer: "Google",
    date: "2024",
    link: "https://www.coursera.org/account/accomplishments/specialization/GE9XM1DZBFLK",
    featured: true
  },
  {
    id: "DVLZVBDMTHGD",
    name: "Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI",
    issuer: "IBM",
    date: "2024",
    link: "https://www.coursera.org/account/accomplishments/verify/DVLZVBDMTHGD",
    featured: true
  },
  {
    id: "5EG74MXD84HR",
    name: "Advanced RAG with Vector Databases and Retrievers",
    issuer: "IBM",
    date: "2024",
    link: "https://www.coursera.org/account/accomplishments/verify/5EG74MXD84HR",
    featured: true
  },
  { id: "WVK5BIFOKD36", name: "Python for Data Science, AI & Development", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/WVK5BIFOKD36", featured: false },
  { id: "HWYYME4N9S1R", name: "Generative AI: Prompt Engineering Basics", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/HWYYME4N9S1R", featured: false },
  { id: "3O07S2XYO5KP", name: "Generative AI: Introduction and Applications", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/3O07S2XYO5KP", featured: false },
  { id: "K7E8E6HC2H6D", name: "AI Agents and MLOps for Production-Ready AI", issuer: "Packt", date: "2024", link: "#", featured: false },
  { id: "7LMUM18TEJL7", name: "Foundations of Model Optimization and Deep Learning", issuer: "Packt", date: "2024", link: "#", featured: false },
  { id: "YCC7VIKSPRVM", name: "AWS Certified DevOps Engineer - Professional", issuer: "Packt", date: "2024", link: "#", featured: false },
  { id: "GAXXE1PN6ER0", name: "Regression Analysis: Simplify Complex Data Relationships", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/GAXXE1PN6ER0", featured: false },
  { id: "RN3MRO84GFP3", name: "Go Beyond the Numbers: Translate Data into Insights", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/RN3MRO84GFP3", featured: false },
  { id: "B5FQDN0QML0V", name: "The Power of Statistics", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/B5FQDN0QML0V", featured: false },
  { id: "JE8Z5RX3U1I6", name: "Foundations of Data Science", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/JE8Z5RX3U1I6", featured: false },
  { id: "OF4SL6NHQUPE", name: "Accelerate Your Job Search with AI", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/OF4SL6NHQUPE", featured: false },
  { id: "C35CH3JUKVX4", name: "Automating Real-World Tasks with Python", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/C35CH3JUKVX4", featured: false },
  { id: "B8MHD2LQUWFV", name: "Configuration Management and the Cloud", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/B8MHD2LQUWFV", featured: false },
  { id: "H6O3KUMOKCZE", name: "Troubleshooting and Debugging Techniques", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/H6O3KUMOKCZE", featured: false },
  { id: "9Y2B1LJK4IOY", name: "Introduction to Git and GitHub", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/9Y2B1LJK4IOY", featured: false },
  { id: "Z7N5GG7A3J31", name: "Using Python to Interact with the Operating System", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/Z7N5GG7A3J31", featured: false },
  { id: "ZVL3JHCGNTLZ", name: "Crash Course on Python", issuer: "Google", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/ZVL3JHCGNTLZ", featured: false },
  { id: "9DHUS500WM11", name: "Build AI Agents using MCP", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/9DHUS500WM11", featured: false },
  { id: "Q9UXHLQMSI4P", name: "Agentic AI with LangChain and LangGraph", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/Q9UXHLQMSI4P", featured: false },
  { id: "2WQ17MW91KQ3", name: "Fundamentals of Building AI Agents", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/2WQ17MW91KQ3", featured: false },
  { id: "OCBYV4IYP59O", name: "Build Multimodal Generative AI Applications", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/OCBYV4IYP59O", featured: false },
  { id: "IA8YYUYNFP7C", name: "Vector Databases for RAG: An Introduction", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/IA8YYUYNFP7C", featured: false },
  { id: "0XCQ3O4AIQQ3", name: "Build RAG Applications: Get Started", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/0XCQ3O4AIQQ3", featured: false },
  { id: "6O5BET9T01CH", name: "Develop Generative AI Applications: Get Started", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/6O5BET9T01CH", featured: false },
  { id: "4d22e718d8854cc6972a7835d864d5f6", name: "SQL and Relational Databases 101", issuer: "Cognitive Class", date: "2024", link: "https://courses.cognitiveclass.ai/certificates/4d22e718d8854cc6972a7835d864d5f6", featured: false },
  { id: "97EGJY7JA3T4", name: "Machine Learning with Python", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/97EGJY7JA3T4", featured: false },
  { id: "7HJICAQ0VF1H", name: "Introduction to Artificial Intelligence (AI)", issuer: "IBM", date: "2024", link: "https://www.coursera.org/account/accomplishments/verify/7HJICAQ0VF1H", featured: false }
];
